name = "linkedin-autoposter-ai"
main = "out/main.js"
compatibility_date = "2025-02-04"
assets = { directory = "./public" }
#routes = [
#    { pattern = "your-domain.com", custom_domain = true },
#]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "autoposter-db"
database_id = "{{db id}}"