services:
  management:
    image: property-management-app
    container_name: management
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 3g
    ports:
      - 8080:8080
      - 9669:9669
    environment:
      - ENVIRONMENT=prod
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE:de
      - LC_ALL=de_DE.UTF-8
    networks:
      - managementnetwork

  db:
    image: postgres:11.1
    container_name: prod-db
    user: root
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
        - ../../postgres-data:/var/lib/postgresql/data
    networks:
      - managementnetwork

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy-config:/etc/caddy/
      - ../../caddy-data:/data
    networks:
      - managementnetwork

networks:
  managementnetwork: