services:
  management:
    image: property-management-app
    container_name: management
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 3g
    ports:
      - 8080:8080
      - 9090:9090
      - 9669:9669
    environment:
      - ENVIRONMENT=prod
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE:de
      - LC_ALL=de_DE.UTF-8
    networks:
      - sharednetwork

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy-config:/etc/caddy/
      - ../../caddy-data:/data
    networks:
      - sharednetwork

networks:
  sharednetwork:
    external: true