version: '3.7'
services:
  hrdata:
    image: management-app
    container_name: management
    ports:
      - 8080:8080
      - 9669:9669
    environment:
      - ENVIRONMENT=prod
    networks:
      - managementnetwork

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy-config:/etc/caddy/
      - ../../caddy-data:/data
    networks:
      - managementnetwork

networks:
  managementnetwork: