version: '3.7'
services:
  db:
    image: postgres:11.1
    user: root
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
        - ./postgresql:/var/lib/postgresql/data