version: '3.7'
services:
  db:
    image: postgres:11.1
    container_name: development-db
    user: root
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=property-management
    restart: always
    ports: 
      - 5432:5432
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - managementnetwork

networks:
  managementnetwork: