-- ============================================
--  USERS / ACCOUNTS TABLE
-- ============================================

-- Remove if exists (D1/SQLite allows DROP TABLE IF EXISTS)
DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    user_id TEXT PRIMARY KEY,               -- UUID generated by CLJS
    email TEXT NOT NULL UNIQUE,             -- Unique constraint
    password TEXT NOT NULL,                 -- hashed with your hash-password function
    veryfied BOOLEAN DEFAULT 0,             -- matches your Clojure code (kept misspelling!)
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Index for login lookups
CREATE INDEX idx_accounts_email ON accounts(email);


-- ============================================
--  SESSION STORE (SQLite version)
--  (Cloudflare D1 does NOT support BYTEA or BIGINT exactly like Postgres)
-- ============================================

DROP TABLE IF EXISTS session_store;

CREATE TABLE session_store (
    session_id TEXT PRIMARY KEY,
    idle_timeout INTEGER,      -- SQLite has no BIGINT; INTEGER is fine
    absolute_timeout INTEGER,
    value BLOB                 -- replaces BYTEA from Postgres
);


-- ============================================
--  OPTIONAL: If you want to track email verification tokens
-- ============================================

DROP TABLE IF EXISTS email_verification_tokens;

CREATE TABLE email_verification_tokens (
    token TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES accounts(user_id)
);

CREATE INDEX idx_verification_user ON email_verification_tokens(user_id);