name: Frontend

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
    #paths:
      #- '.github/workflows/frontend.yml'
      #- 'bases/frontend/**'
jobs:
  build:
    name: Build with shadow-cljs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.11.1.1347
      - name: Build the application
        run: |
            cd ./bases/frontend/
            npm install
            npx babel ./ui --out-dir ./js --extensions ".ts,.tsx,.jsx" --ignore "node_modules"
            npm run release
            cp -R resources/public/ out/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: compilation
            path: ./bases/frontend/out/

  deploy:
    name: Deploy the app
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: compilation
      # Deploy to Hetzner
      - name: install ssh keys
        # check this thread to understand why its needed:
        # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Copy frontend compiled code the VM
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " \
          if [ -d ~/static-content/${{ secrets.WORK_DIR }} ]; then 
            rm -rf ~/static-content/${{ secrets.WORK_DIR }}
          fi
          
          mkdir ~/static-content/${{ secrets.WORK_DIR }}
          exit"
          scp -o StrictHostKeyChecking=no -r ./public ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:static-content/${{ secrets.WORK_DIR }}